export const ROUTES = [
  { method: "GET",    path: "/health",       description: "存活探测（免 token）" },
  { method: "POST",   path: "/shutdown",     description: "优雅退出 daemon" },
  { method: "GET",    path: "/projects",     description: "列出已保存项目" },
  { method: "POST",   path: "/projects",     description: "保存项目 {repoRoot}" },
  { method: "DELETE", path: "/projects/:id", description: "忘记项目（只删记录）" },
  { method: "GET",    path: "/events",       description: "事件流游标读取 ?after=&limit=&workspace=" },
  { method: "GET",    path: "/workspaces",               description: "列出 workspace ?project=" },
  { method: "POST",   path: "/workspaces",               description: "创建 workspace {projectId, branchSlug?, name?, initialPrompt?}（同步跑完流水线才返回）" },
  { method: "POST",   path: "/workspaces/:id/archive",   description: "归档：删 worktree 留 branch {force?}" },
  { method: "POST",   path: "/workspaces/:id/unarchive", description: "从保留的 branch 重建 worktree" },
  { method: "POST",   path: "/workspaces/:id/retry",     description: "error 状态重跑创建流水线" },
  { method: "DELETE", path: "/workspaces/:id",           description: "删 worktree+记录，branch 保留 ?force=1" },
  { method: "GET",    path: "/events/stream",            description: "SSE：durable replay + live 推送 ?after=&workspace=" },
  { method: "GET",  path: "/workspaces/:id/tabs", description: "列出 workspace 的 tabs（GUI tab ↔ tmux window 映射）" },
  { method: "POST", path: "/hooks/claude",        description: "claude hook 回调 ?workspace=（结构化 engine 状态唯一入口）" },
  { method: "GET",  path: "/config",                        description: "client 引导信息：tmuxSocket + engines（能力位/模型列表）" },
  { method: "GET",  path: "/workspaces/:id/git/diffstat",   description: "vs baseRef 的 shortstat（左栏 +N−M 轮询）" },
  { method: "GET",  path: "/workspaces/:id/git/changes",    description: "四分区 numstat：against-base/committed/staged/unstaged + untracked" },
  { method: "GET",  path: "/workspaces/:id/files",          description: "worktree 文件列表（@文件选择器/Files 树）" },
  { method: "GET",  path: "/workspaces/:id/commands",       description: "slash 命令扫描：repo .claude/commands + ~/.claude/commands" },
  { method: "GET",  path: "/ws/terminal",         description: "WS 终端通道 ?workspace=&window=&cols=&rows=&token=（二进制帧+JSON 控制帧）" },
] as const satisfies ReadonlyArray<{ method: "GET" | "POST" | "DELETE"; path: string; description: string }>
